### ISSUE TITLE
Fullscreen doesn't work for local html files

### ISSUE THREAD

**Issue by ghost** [MarkTiedemann/fullscreen#1] opened 2019-11-27 12:59 UTC
Here is the most simple HTML file that validates perfectly on https://validator.w3.org. But the fullscreen plugin doesn't work on it unless it is hosted on a website (I'm assuming).

```
<!DOCTYPE html>
<html lang="en">
<head>
<title>
Test Page
</title>
</head>
<body>
Body text.
</body>
</html>

```

**Comment by MarkTiedemann** [comment] 2019-11-27 14:38
Yeah, I believe the `requestFullscreen` API doesn't work for `file://` URLs in Firefox.

Closing, as there's nothing I can do to fix this. Sorry about that.

**Comment by ghost** [comment] 2019-11-27 16:37
No problem. This one works somehow https://addons.mozilla.org/ga-IE/firefox/addon/fullscreen_plus/?src=search

**Comment by MarkTiedemann** [comment] 2019-11-27 17:40
Thanks for showing me that this does indeed work. Because of that, I investigated again. The issue is in the manifest: https://github.com/MarkTiedemann/fullscreen/blob/master/manifest.json#L12 The extension is only loaded for `https://` rather than all URLs. I will fix this and release an update soon.

Thanks again, @tenleftfingers!

**Closed as completed** 2019-11-27 18:16 UTC

**Comment by MarkTiedemann** [comment] 2019-11-27 18:45
Just submitted v0.2 for release. Might take a while until you can see it in the app store.

**Comment by ghost** [comment] 2019-11-27 21:07
That was lightning fast; both to find the issue and release a fix. Thank you very much, looking forward to it @MarkTiedemann ! :)

**Comment by MarkTiedemann** [comment] 2019-11-27 23:37
Cheers, @tenleftfingers - the new version is online!
